<a href="https://colab.research.google.com/github/Udayan-12/AI.Assisted.Coding/blob/main/lab.17.3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Assuming the employee dataset is in a CSV file named 'employee_data.csv'
# If your file has a different name or path, please update it here.
try:
    df = pd.read_csv('employee_data.csv')
    print("Dataset loaded successfully.")
except FileNotFoundError:
    print("Error: 'employee_data.csv' not found. Please upload the file or provide the correct path/name.")
    # Creating a sample DataFrame for demonstration purposes if the file is not found
    data = {
        'employee_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy'],
        'salary': [70000, 80000, None, 60000, 95000, 72000, 88000, None, 65000, 78000],
        'designation': ['Software Engineer', 'Project Manager', 'Data Scientist', 'Software Engineer', 'HR Manager', 'Project Manager', 'Data Scientist', 'Software Engineer', 'HR Manager', 'Data Scientist'],
        'experience_years': [5, 10, 3, 4, 7, 6, None, 2, 8, 5],
        'employment_type': ['Full-time', 'Full-time', 'Contract', 'Full-time', 'Full-time', 'Contract', 'Full-time', 'Full-time', 'Part-time', 'Full-time'],
        'job_title': ['Software Engineer', 'Project Manager', 'Data Scientist', 'software engineer', 'HR Manager', 'project manager', 'Data Scientist', 'Software Engineer', 'hr manager', 'Data Scientist']
    }
    df = pd.DataFrame(data)
    print("A sample DataFrame has been created for demonstration.")


print("\nFirst 5 rows of the dataset:")
display(df.head())

print("\nDataset information (columns, non-null counts, dtypes):")
df.info()

Error: 'employee_data.csv' not found. Please upload the file or provide the correct path/name.
A sample DataFrame has been created for demonstration.

First 5 rows of the dataset:

,employee_id,name,salary,designation,experience_years,employment_type,job_title
0,1,Alice,70000.0,Software Engineer,5.0,Full-time,Software Engineer
1,2,Bob,80000.0,Project Manager,10.0,Full-time,Project Manager
2,3,Charlie,NaN,Data Scientist,3.0,Contract,Data Scientist
3,4,David,60000.0,Software Engineer,4.0,Full-time,software engineer
4,5,Eve,95000.0,HR Manager,7.0,Full-time,HR Manager

Dataset information (columns, non-null counts, dtypes):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   employee_id       10 non-null     int64
 1   name              10 non-null     object
 2   salary            8 non-null      float64
 3   designation       10 non-null     object
 4   experience_years  9 non-null      float64
 5   employment_type   10 non-null     object
 6   job_title         10 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 692.0+ bytes

In [4]:
# 3. Standardize text values (job titles in lowercase)
df['job_title'] = df['job_title'].str.lower()
print("\n'job_title' column after standardizing to lowercase:")
display(df[['job_title']].head())

# 4. Encode categorical features
# One-hot encoding for 'designation' and 'employment_type'
df = pd.get_dummies(df, columns=['designation', 'employment_type'], drop_first=True)

print("\nDataFrame after one-hot encoding categorical features:")
display(df.head())
df.info()

'job_title' column after standardizing to lowercase:

           job_title
0  software engineer
1    project manager
2     data scientist
3  software engineer
4         hr manager

DataFrame after one-hot encoding categorical features:

,employee_id,name,salary,experience_years,job_title,designation_HR Manager,designation_Project Manager,designation_Software Engineer,employment_type_Full-time,employment_type_Part-time
0,1,Alice,70000.0,5.0,software engineer,False,False,True,True,False
1,2,Bob,80000.0,10.0,project manager,False,True,False,True,False
2,3,Charlie,75000.0,3.0,data scientist,False,False,False,False,False
3,4,David,60000.0,4.0,software engineer,False,False,True,True,False
4,5,Eve,95000.0,7.0,hr manager,True,False,False,True,False

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   employee_id                    10 non-null     int64
 1   name                           10 non-null     object
 2   salary                         10 non-null     float64
 3   experience_years               10 non-null     float64
 4   job_title                      10 non-null     object
 5   designation_HR Manager         10 non-null     bool
 6   designation_Project Manager    10 non-null     bool
 7   designation_Software Engineer  10 non-null     bool
 8   employment_type_Full-time      10 non-null     bool
 9   employment_type_Part-time      10 non-null     bool
dtypes: bool(5), float64(2), int64(1), object(2)
memory usage: 582.0+ bytes

In [3]:
# 1. Handle missing values
# Impute missing 'salary' values with the median
median_salary = df['salary'].median()
df['salary'] = df['salary'].fillna(median_salary)
print(f"Missing 'salary' values imputed with median: {median_salary}")

# Impute missing 'experience_years' values with the median
median_experience = df['experience_years'].median()
df['experience_years'] = df['experience_years'].fillna(median_experience)
print(f"Missing 'experience_years' values imputed with median: {median_experience}")

print("\nAfter handling missing values:")
df.info()

# 2. Remove duplicate employee IDs
initial_rows = len(df)
df.drop_duplicates(subset=['employee_id'], inplace=True)
duplicates_removed = initial_rows - len(df)

if duplicates_removed > 0:
    print(f"\nRemoved {duplicates_removed} duplicate employee ID(s).")
else:
    print("\nNo duplicate employee IDs found.")

print("\nAfter removing duplicates:")
display(df.head())
df.info()

Missing 'salary' values imputed with median: 75000.0
Missing 'experience_years' values imputed with median: 5.0

After handling missing values:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   employee_id       10 non-null     int64
 1   name              10 non-null     object
 2   salary            10 non-null     float64
 3   designation       10 non-null     object
 4   experience_years  10 non-null     float64
 5   employment_type   10 non-null     object
 6   job_title         10 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 692.0+ bytes

No duplicate employee IDs found.

After removing duplicates:

,employee_id,name,salary,designation,experience_years,employment_type,job_title
0,1,Alice,70000.0,Software Engineer,5.0,Full-time,Software Engineer
1,2,Bob,80000.0,Project Manager,10.0,Full-time,Project Manager
2,3,Charlie,75000.0,Data Scientist,3.0,Contract,Data Scientist
3,4,David,60000.0,Software Engineer,4.0,Full-time,software engineer
4,5,Eve,95000.0,HR Manager,7.0,Full-time,HR Manager

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   employee_id       10 non-null     int64
 1   name              10 non-null     object
 2   salary            10 non-null     float64
 3   designation       10 non-null     object
 4   experience_years  10 non-null     float64
 5   employment_type   10 non-null     object
 6   job_title         10 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 692.0+ bytes

In [7]:
import pandas as pd
import numpy as np

# Creating a sample student performance DataFrame
np.random.seed(42)
data = {
    'student_id': range(1, 21),
    'exam_date': pd.to_datetime(pd.date_range(start='2023-01-15', periods=20, freq='W').strftime('%Y-%m-%d')).astype(str).tolist(), # Convert to string to simulate initial state
    'subject': np.random.choice(['Math', 'Science', 'English', 'History'], 20),
    'total_marks': np.random.randint(40, 100, 20).tolist(),
    'attendance_percentage': np.random.uniform(70, 100, 20).round(1).tolist()
}

# Create the DataFrame first
df_student = pd.DataFrame(data)

# Introduce some outliers in total_marks directly in the DataFrame
indices_to_change = np.random.choice(len(df_student['total_marks']), 2, replace=False)
df_student.loc[indices_to_change, 'total_marks'] = [10, 120] # Low and high outliers

print("Sample Student Performance DataFrame created:")
display(df_student.head())
print("\nDataFrame Information before preprocessing:")
df_student.info()


# 1. Convert 'exam_date' column into datetime format
df_student['exam_date'] = pd.to_datetime(df_student['exam_date'])
print("\n'exam_date' column converted to datetime:")
df_student.info()

# 2. Extract new features (month, semester, day)
df_student['exam_month'] = df_student['exam_date'].dt.month
df_student['exam_day_of_week'] = df_student['exam_date'].dt.day_name()

# For semester, let's define a simple rule (e.g., Jan-June as Semester 1, July-Dec as Semester 2)
df_student['semester'] = df_student['exam_date'].apply(lambda x: 'Semester 1' if x.month <= 6 else 'Semester 2')

print("\nDataFrame after extracting new time-based features:")
display(df_student.head())

Sample Student Performance DataFrame created:

   student_id   exam_date  subject  total_marks  attendance_percentage
0           1  2023-01-15  English           61                   71.4
1           2  2023-01-22  History           92                   99.2
2           3  2023-01-29     Math           41                   77.0
3           4  2023-02-05  English           63                   72.7
4           5  2023-02-12  English           83                   88.6

DataFrame Information before preprocessing:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             20 non-null     int64
 1   exam_date              20 non-null     object
 2   subject                20 non-null     object
 3   total_marks            20 non-null     int64
 4   attendance_percentage  20 non-null     float64
dtypes: float64(1), int64(2), object(2)
memory usage: 932.0+ bytes

'exam_date' column converted to datetime:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             20 non-null     int64
 1   exam_date              20 non-null     datetime64[ns]
 2   subject                20 non-null     object
 3   total_marks            20 non-null     int64
 4   attendance_percentage  20 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(1)
memory usage: 932.0+ bytes

DataFrame after extracting new time-based features:

,student_id,exam_date,subject,total_marks,attendance_percentage,exam_month,exam_day_of_week,semester
0,1,2023-01-15,English,61,71.4,1,Sunday,Semester 1
1,2,2023-01-22,History,92,99.2,1,Sunday,Semester 1
2,3,2023-01-29,Math,41,77.0,1,Sunday,Semester 1
3,4,2023-02-05,English,63,72.7,2,Sunday,Semester 1
4,5,2023-02-12,English,83,88.6,2,Sunday,Semester 1

In [10]:
# 1. Handle missing values
# Impute missing 'height_cm', 'weight_kg', and 'BMI' values with the median

median_height = df_health['height_cm'].median()
df_health['height_cm'] = df_health['height_cm'].fillna(median_height)
print(f"Missing 'height_cm' values imputed with median: {median_height}")

median_weight = df_health['weight_kg'].median()
df_health['weight_kg'] = df_health['weight_kg'].fillna(median_weight)
print(f"Missing 'weight_kg' values imputed with median: {median_weight}")

median_bmi = df_health['BMI'].median()
df_health['BMI'] = df_health['BMI'].fillna(median_bmi)
print(f"Missing 'BMI' values imputed with median: {median_bmi}")

print("\nDataFrame after handling missing values:")
df_health.info()
display(df_health.head())

Missing 'height_cm' values imputed with median: 168.8
Missing 'weight_kg' values imputed with median: 72.65
Missing 'BMI' values imputed with median: 23.59861349392529

DataFrame after handling missing values:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   student_id         20 non-null     int64
 1   age                20 non-null     int64
 2   height_cm          20 non-null     float64
 3   weight_kg          20 non-null     float64
 4   medical_condition  20 non-null     object
 5   fitness_status     20 non-null     object
 6   BMI                20 non-null     float64
dtypes: float64(3), int64(2), object(2)
memory usage: 1.2+ KB

,student_id,age,height_cm,weight_kg,medical_condition,fitness_status,BMI
0,1,24,168.8,78.50,None,Good,23.598613
1,2,21,165.7,72.65,None,Good,23.598613
2,3,22,164.7,49.30,None,Good,18.174385
3,4,24,168.8,64.70,None,Good,22.706981
4,5,20,172.2,63.10,None,Poor,21.279581

In [18]:
# 4. Detect and handle outliers using the IQR method

Q1 = df_student['total_marks'].quantile(0.25)
Q3 = df_student['total_marks'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"Q1 (25th percentile) for total_marks: {Q1}")
print(f"Q3 (75th percentile) for total_marks: {Q3}")
print(f"IQR: {IQR}")
print(f"Lower Bound for outliers: {lower_bound}")
print(f"Upper Bound for outliers: {upper_bound}")

# Identify outliers
outliers = df_student[(df_student['total_marks'] < lower_bound) | (df_student['total_marks'] > upper_bound)]

if not outliers.empty:
    print(f"\nDetected {len(outliers)} outliers in 'total_marks':")
    display(outliers[['student_id', 'total_marks']])

    # Cap outliers (replace values outside bounds with the bounds)
    df_student['total_marks_capped'] = df_student['total_marks'].clip(lower=lower_bound, upper=upper_bound)
    print("\n'total_marks' column after capping outliers:")
    display(df_student[['total_marks', 'total_marks_capped']].head())
    print(f"Number of values changed due to capping: {sum(df_student['total_marks'] != df_student['total_marks_capped'])}")
else:
    print("\nNo significant outliers detected in 'total_marks' using the IQR method.")

df_student.info()

Q1 (25th percentile) for total_marks: 60.75
Q3 (75th percentile) for total_marks: 89.0
IQR: 28.25
Lower Bound for outliers: 18.375
Upper Bound for outliers: 131.375

Detected 1 outliers in 'total_marks':

    student_id  total_marks
15          16           10

'total_marks' column after capping outliers:

   total_marks  total_marks_capped
0           61                61.0
1           92                92.0
2           41                41.0
3           63                63.0
4           83                83.0

Number of values changed due to capping: 1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              20 non-null     int64
 1   exam_date               20 non-null     datetime64[ns]
 2   subject                 20 non-null     object
 3   total_marks             20 non-null     int64
 4   attendance_percentage   20 non-null     float64
 5   exam_month              20 non-null     int32
 6   exam_day_of_week        20 non-null     object
 7   semester                20 non-null     object
 8   total_marks_normalized  20 non-null     float64
 9   total_marks_capped      20 non-null     float64
dtypes: datetime64[ns](1), float64(3), int32(1), int64(2), object(3)
memory usage: 1.6+ KB

In [17]:
# 3. Normalize 'total_marks' using Min-Max Scaling
from sklearn.preprocessing import MinMaxScaler

scaler_minmax = MinMaxScaler()
df_student['total_marks_normalized'] = scaler_minmax.fit_transform(df_student[['total_marks']])

print("\nDataFrame after normalizing 'total_marks':")
display(df_student.head())

DataFrame after normalizing 'total_marks':

,student_id,exam_date,subject,total_marks,attendance_percentage,exam_month,exam_day_of_week,semester,total_marks_normalized
0,1,2023-01-15,English,61,71.4,1,Sunday,Semester 1,0.463636
1,2,2023-01-22,History,92,99.2,1,Sunday,Semester 1,0.745455
2,3,2023-01-29,Math,41,77.0,1,Sunday,Semester 1,0.281818
3,4,2023-02-05,English,63,72.7,2,Sunday,Semester 1,0.481818
4,5,2023-02-12,English,83,88.6,2,Sunday,Semester 1,0.663636

In [15]:
# 4. Split dataset into training and testing sets
from sklearn.model_selection import train_test_split

# Assuming 'student_id' is just an identifier and not a feature for training
# Also, we don't have a specific target variable mentioned yet, so we'll just split features for now.
# If a target variable (e.g., 'fitness_status') were to be predicted, we'd separate X and y.

X = df_health.drop('student_id', axis=1) # Drop identifier column

# Splitting the data into training and testing sets (e.g., 80% train, 20% test)
X_train, X_test = train_test_split(X, test_size=0.2, random_state=42)

print(f"\nShape of training set (X_train): {X_train.shape}")
print(f"Shape of testing set (X_test): {X_test.shape}")

print("\nFirst 5 rows of X_train:")
display(X_train.head())
print("\nFirst 5 rows of X_test:")
display(X_test.head())

Shape of training set (X_train): (16, 10)
Shape of testing set (X_test): (4, 10)

First 5 rows of X_train:

,age,height_cm,weight_kg,BMI,medical_condition_Asthma,medical_condition_Diabetes,medical_condition_None,fitness_status_Excellent,fitness_status_Good,fitness_status_Poor
8,-1.535738,1.556526,0.500539,-0.096570,True,False,False,False,True,False
5,0.307148,-0.753942,-0.170141,0.378211,False,False,True,False,False,False
11,-0.921443,2.505034,-0.053654,-0.268506,False,False,False,True,False,False
3,1.535738,0.036481,-0.614907,-0.440366,False,False,True,False,True,False
18,-1.535738,-0.291849,-1.836251,-1.505552,True,False,False,True,False,False

First 5 rows of X_test:

,age,height_cm,weight_kg,BMI,medical_condition_Asthma,medical_condition_Diabetes,medical_condition_None,fitness_status_Excellent,fitness_status_Good,fitness_status_Poor
0,1.535738,0.036481,0.359343,-0.268506,False,False,True,False,True,False
17,0.307148,0.632339,-0.148962,-0.262182,False,False,True,False,False,False
15,-0.921443,-1.155234,1.495969,2.395407,False,False,True,False,True,False
1,-0.307148,-0.340490,-0.053654,-0.268506,False,False,True,False,True,False

In [16]:
# 4. Split dataset into training and testing sets
from sklearn.model_selection import train_test_split

# Assuming 'student_id' is just an identifier and not a feature for training
# Also, we don't have a specific target variable mentioned yet, so we'll just split features for now.
# If a target variable (e.g., 'fitness_status') were to be predicted, we'd separate X and y.

X = df_health.drop('student_id', axis=1) # Drop identifier column

# Splitting the data into training and testing sets (e.g., 80% train, 20% test)
X_train, X_test = train_test_split(X, test_size=0.2, random_state=42)

print(f"\nShape of training set (X_train): {X_train.shape}")
print(f"Shape of testing set (X_test): {X_test.shape}")

print("\nFirst 5 rows of X_train:")
display(X_train.head())
print("\nFirst 5 rows of X_test:")
display(X_test.head())

Shape of training set (X_train): (16, 10)
Shape of testing set (X_test): (4, 10)

First 5 rows of X_train:

,age,height_cm,weight_kg,BMI,medical_condition_Asthma,medical_condition_Diabetes,medical_condition_None,fitness_status_Excellent,fitness_status_Good,fitness_status_Poor
8,-1.535738,1.556526,0.500539,-0.096570,True,False,False,False,True,False
5,0.307148,-0.753942,-0.170141,0.378211,False,False,True,False,False,False
11,-0.921443,2.505034,-0.053654,-0.268506,False,False,False,True,False,False
3,1.535738,0.036481,-0.614907,-0.440366,False,False,True,False,True,False
18,-1.535738,-0.291849,-1.836251,-1.505552,True,False,False,True,False,False

First 5 rows of X_test:

,age,height_cm,weight_kg,BMI,medical_condition_Asthma,medical_condition_Diabetes,medical_condition_None,fitness_status_Excellent,fitness_status_Good,fitness_status_Poor
0,1.535738,0.036481,0.359343,-0.268506,False,False,True,False,True,False
17,0.307148,0.632339,-0.148962,-0.262182,False,False,True,False,False,False
15,-0.921443,-1.155234,1.495969,2.395407,False,False,True,False,True,False
1,-0.307148,-0.340490,-0.053654,-0.268506,False,False,True,False,True,False

In [13]:
# 3. Scale numerical features using standard scaling
from sklearn.preprocessing import StandardScaler

# Identify numerical columns to scale (excluding 'student_id' and boolean columns from one-hot encoding)
numerical_cols = ['age', 'height_cm', 'weight_kg', 'BMI']

# Initialize StandardScaler
scaler = StandardScaler()

# Apply scaling to the numerical columns
df_health[numerical_cols] = scaler.fit_transform(df_health[numerical_cols])

print("\nDataFrame after scaling numerical features:")
display(df_health.head())
df_health.info()

DataFrame after scaling numerical features:

,student_id,age,height_cm,weight_kg,BMI,medical_condition_Asthma,medical_condition_Diabetes,medical_condition_None,fitness_status_Excellent,fitness_status_Good,fitness_status_Poor
0,1,1.535738,0.036481,0.359343,-0.268506,False,False,True,False,True,False
1,2,-0.307148,-0.340490,-0.053654,-0.268506,False,False,True,False,True,False
2,3,0.307148,-0.462094,-1.702115,-1.314009,False,False,True,False,True,False
3,4,1.535738,0.036481,-0.614907,-0.440366,False,False,True,False,True,False
4,5,-0.921443,0.449933,-0.727864,-0.715493,False,False,True,False,False,True

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  20 non-null     int64
 1   age                         20 non-null     float64
 2   height_cm                   20 non-null     float64
 3   weight_kg                   20 non-null     float64
 4   BMI                         20 non-null     float64
 5   medical_condition_Asthma    20 non-null     bool
 6   medical_condition_Diabetes  20 non-null     bool
 7   medical_condition_None      20 non-null     bool
 8   fitness_status_Excellent    20 non-null     bool
 9   fitness_status_Good         20 non-null     bool
 10  fitness_status_Poor         20 non-null     bool
dtypes: bool(6), float64(4), int64(1)
memory usage: 1.0 KB

In [14]:
# 3. Scale numerical features using standard scaling
from sklearn.preprocessing import StandardScaler

# Identify numerical columns to scale (excluding 'student_id' and boolean columns from one-hot encoding)
numerical_cols = ['age', 'height_cm', 'weight_kg', 'BMI']

# Initialize StandardScaler
scaler = StandardScaler()

# Apply scaling to the numerical columns
df_health[numerical_cols] = scaler.fit_transform(df_health[numerical_cols])

print("\nDataFrame after scaling numerical features:")
display(df_health.head())
df_health.info()

DataFrame after scaling numerical features:

,student_id,age,height_cm,weight_kg,BMI,medical_condition_Asthma,medical_condition_Diabetes,medical_condition_None,fitness_status_Excellent,fitness_status_Good,fitness_status_Poor
0,1,1.535738,0.036481,0.359343,-0.268506,False,False,True,False,True,False
1,2,-0.307148,-0.340490,-0.053654,-0.268506,False,False,True,False,True,False
2,3,0.307148,-0.462094,-1.702115,-1.314009,False,False,True,False,True,False
3,4,1.535738,0.036481,-0.614907,-0.440366,False,False,True,False,True,False
4,5,-0.921443,0.449933,-0.727864,-0.715493,False,False,True,False,False,True

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  20 non-null     int64
 1   age                         20 non-null     float64
 2   height_cm                   20 non-null     float64
 3   weight_kg                   20 non-null     float64
 4   BMI                         20 non-null     float64
 5   medical_condition_Asthma    20 non-null     bool
 6   medical_condition_Diabetes  20 non-null     bool
 7   medical_condition_None      20 non-null     bool
 8   fitness_status_Excellent    20 non-null     bool
 9   fitness_status_Good         20 non-null     bool
 10  fitness_status_Poor         20 non-null     bool
dtypes: bool(6), float64(4), int64(1)
memory usage: 1.0 KB

In [11]:
# 2. Encode categorical features
# One-hot encoding for 'medical_condition' and 'fitness_status'
df_health = pd.get_dummies(df_health, columns=['medical_condition', 'fitness_status'], drop_first=True)

print("\nDataFrame after one-hot encoding categorical features:")
display(df_health.head())
df_health.info()

DataFrame after one-hot encoding categorical features:

,student_id,age,height_cm,weight_kg,BMI,medical_condition_Asthma,medical_condition_Diabetes,medical_condition_None,fitness_status_Excellent,fitness_status_Good,fitness_status_Poor
0,1,24,168.8,78.50,23.598613,False,False,True,False,True,False
1,2,21,165.7,72.65,23.598613,False,False,True,False,True,False
2,3,22,164.7,49.30,18.174385,False,False,True,False,True,False
3,4,24,168.8,64.70,22.706981,False,False,True,False,True,False
4,5,20,172.2,63.10,21.279581,False,False,True,False,False,True

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  20 non-null     int64
 1   age                         20 non-null     int64
 2   height_cm                   20 non-null     float64
 3   weight_kg                   20 non-null     float64
 4   BMI                         20 non-null     float64
 5   medical_condition_Asthma    20 non-null     bool
 6   medical_condition_Diabetes  20 non-null     bool
 7   medical_condition_None      20 non-null     bool
 8   fitness_status_Excellent    20 non-null     bool
 9   fitness_status_Good         20 non-null     bool
 10  fitness_status_Poor         20 non-null     bool
dtypes: bool(6), float64(3), int64(2)
memory usage: 1.0 KB

In [12]:
# 2. Encode categorical features
# One-hot encoding for 'medical_condition' and 'fitness_status'
df_health = pd.get_dummies(df_health, columns=['medical_condition', 'fitness_status'], drop_first=True)

print("\nDataFrame after one-hot encoding categorical features:")
display(df_health.head())
df_health.info()

KeyError: "None of [Index(['medical_condition', 'fitness_status'], dtype='object')] are in the [columns]"

In [9]:
import pandas as pd
import numpy as np

# Set a random seed for reproducibility
np.random.seed(42)

# Generate sample data for student health records
data_health = {
    'student_id': range(1, 21),
    'age': np.random.randint(18, 25, 20),
    'height_cm': np.random.normal(170, 10, 20).round(1),
    'weight_kg': np.random.normal(70, 15, 20).round(1),
    'medical_condition': np.random.choice(['None', 'Asthma', 'Diabetes', 'Allergies'], 20, p=[0.6, 0.2, 0.1, 0.1]),
    'fitness_status': np.random.choice(['Excellent', 'Good', 'Average', 'Poor'], 20, p=[0.25, 0.35, 0.3, 0.1])
}

df_health = pd.DataFrame(data_health)

# Introduce some missing values for demonstration
missing_indices_height = np.random.choice(df_health.index, 3, replace=False)
missing_indices_weight = np.random.choice(df_health.index, 2, replace=False)

df_health.loc[missing_indices_height, 'height_cm'] = np.nan
df_health.loc[missing_indices_weight, 'weight_kg'] = np.nan

# Calculate BMI, which will also have missing values if height or weight is missing
df_health['BMI'] = df_health['weight_kg'] / ((df_health['height_cm'] / 100) ** 2)

print("Sample Student Health DataFrame created:")
display(df_health.head())
print("\nDataFrame Information:")
df_health.info()

Sample Student Health DataFrame created:

,student_id,age,height_cm,weight_kg,medical_condition,fitness_status,BMI
0,1,24,NaN,78.5,None,Good,NaN
1,2,21,165.7,NaN,None,Good,NaN
2,3,22,164.7,49.3,None,Good,18.174385
3,4,24,168.8,64.7,None,Good,22.706981
4,5,20,172.2,63.1,None,Poor,21.279581

DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   student_id         20 non-null     int64
 1   age                20 non-null     int64
 2   height_cm          17 non-null     float64
 3   weight_kg          18 non-null     float64
 4   medical_condition  20 non-null     object
 5   fitness_status     20 non-null     object
 6   BMI                15 non-null     float64
dtypes: float64(3), int64(2), object(2)
memory usage: 1.2+ KB

In [19]:
import pandas as pd
import numpy as np

# Set a random seed for reproducibility
np.random.seed(42)

# Generate sample data for ride-sharing
data_rideshare = {
    'ride_id': range(101, 121),
    'pickup_location': [
        '  Downtown ',
        'Airport',
        'suburbia',
        'downtown',
        'Uptown',
        'Airport ',
        'SUBURBIA',
        'Downtown',
        'airport',
        'Uptown',
        'Downtown',
        'Suburbia',
        'Airport',
        'Uptown',
        'Downtown',
        'Airport',
        'Suburbia',
        'Uptown',
        'Downtown',
        'Airport'
    ],
    'dropoff_location': [
        'Uptown',
        'Downtown',
        'Airport',
        'Uptown ',
        'Downtown',
        'suburbia',
        'Airport',
        'Uptown',
        'Downtown',
        'Airport',
        'Uptown',
        'Downtown',
        'Airport',
        'Uptown',
        'Downtown',
        'Airport',
        'Uptown',
        'Downtown',
        'Airport',
        'Uptown'
    ],
    'fare_amount': np.random.normal(25, 10, 20).round(2),
    'driver_rating': np.random.uniform(2.5, 5.0, 20).round(1),
    'trip_duration_minutes': np.random.randint(10, 60, 20)
}

df_rideshare = pd.DataFrame(data_rideshare)

# Introduce some missing values
missing_fare_indices = np.random.choice(df_rideshare.index, 3, replace=False)
df_rideshare.loc[missing_fare_indices, 'fare_amount'] = np.nan

# Introduce some duplicate entries (based on ride_id and other key features)
duplicate_rows = df_rideshare.sample(2, random_state=1).copy()
duplicate_rows['ride_id'] = [121, 122] # Assign new ride_ids for duplicates for realism
df_rideshare = pd.concat([df_rideshare, duplicate_rows], ignore_index=True)

# Introduce some inconsistent driver ratings (outside typical 1-5 scale or just unusual)
# Let's say one driver got a 0.5 and another a 5.2
df_rideshare.loc[np.random.choice(df_rideshare.index, 1), 'driver_rating'] = 0.5
df_rideshare.loc[np.random.choice(df_rideshare.index, 1), 'driver_rating'] = 5.2

print("Sample Ride-Sharing DataFrame created:")
display(df_rideshare.head(10))
print("\nDataFrame Information:")
df_rideshare.info()

Sample Ride-Sharing DataFrame created:

,ride_id,pickup_location,dropoff_location,fare_amount,driver_rating,trip_duration_minutes
0,101,Downtown,Uptown,29.97,3.6,45
1,102,Airport,Downtown,23.62,4.5,59
2,103,suburbia,Airport,NaN,3.0,49
3,104,downtown,Uptown,40.23,3.8,13
4,105,Uptown,Downtown,22.66,4.0,11
5,106,Airport,suburbia,22.66,2.6,15
6,107,SUBURBIA,Airport,40.79,4.0,51
7,108,Downtown,Uptown,32.67,2.9,13
8,109,airport,Downtown,20.31,2.7,38
9,110,Uptown,Airport,30.43,4.9,27

DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ride_id                22 non-null     int64
 1   pickup_location        22 non-null     object
 2   dropoff_location       22 non-null     object
 3   fare_amount            19 non-null     float64
 4   driver_rating          22 non-null     float64
 5   trip_duration_minutes  22 non-null     int64
dtypes: float64(2), int64(2), object(2)
memory usage: 1.2+ KB

In [23]:
# 4. Normalize driver ratings using Min-Max Scaling
from sklearn.preprocessing import MinMaxScaler

# Initialize MinMaxScaler
scaler_driver_rating = MinMaxScaler()

# Reshape the column for scaling (MinMaxScaler expects a 2D array)
df_rideshare['driver_rating_normalized'] = scaler_driver_rating.fit_transform(df_rideshare[['driver_rating']])

print("\nDataFrame after normalizing 'driver_rating':")
display(df_rideshare[['driver_rating', 'driver_rating_normalized']].head())
df_rideshare.info()

DataFrame after normalizing 'driver_rating':

   driver_rating  driver_rating_normalized
0            3.6                  0.659574
1            4.5                  0.851064
2            3.0                  0.531915
3            3.8                  0.702128
4            4.0                  0.744681

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ride_id                   22 non-null     int64
 1   pickup_location           22 non-null     object
 2   dropoff_location          22 non-null     object
 3   fare_amount               22 non-null     float64
 4   driver_rating             22 non-null     float64
 5   trip_duration_minutes     22 non-null     int64
 6   driver_rating_normalized  22 non-null     float64
dtypes: float64(3), int64(2), object(2)
memory usage: 1.3+ KB

In [22]:
# 3. Remove duplicate ride entries
initial_rows_rideshare = len(df_rideshare)
df_rideshare.drop_duplicates(subset=['ride_id', 'pickup_location', 'dropoff_location', 'trip_duration_minutes'], inplace=True)
duplicates_removed_rideshare = initial_rows_rideshare - len(df_rideshare)

if duplicates_removed_rideshare > 0:
    print(f"Removed {duplicates_removed_rideshare} duplicate ride entry(s).")
else:
    print("No duplicate ride entries found.")

print("\nDataFrame after removing duplicates:")
display(df_rideshare.head())
df_rideshare.info()

No duplicate ride entries found.

DataFrame after removing duplicates:

,ride_id,pickup_location,dropoff_location,fare_amount,driver_rating,trip_duration_minutes
0,101,Downtown,Uptown,29.97,3.6,45
1,102,Airport,Downtown,23.62,4.5,59
2,103,Suburbia,Airport,22.66,3.0,49
3,104,Downtown,Uptown,40.23,3.8,13
4,105,Uptown,Downtown,22.66,4.0,11

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ride_id                22 non-null     int64
 1   pickup_location        22 non-null     object
 2   dropoff_location       22 non-null     object
 3   fare_amount            22 non-null     float64
 4   driver_rating          22 non-null     float64
 5   trip_duration_minutes  22 non-null     int64
dtypes: float64(2), int64(2), object(2)
memory usage: 1.2+ KB

In [21]:
# 2. Fill missing fare amounts with median values
median_fare = df_rideshare['fare_amount'].median()
df_rideshare['fare_amount'] = df_rideshare['fare_amount'].fillna(median_fare)

print(f"Missing 'fare_amount' values imputed with median: {median_fare}")
print("\nDataFrame after filling missing fare amounts:")
display(df_rideshare.head())
df_rideshare.info()

Missing 'fare_amount' values imputed with median: 22.66

DataFrame after filling missing fare amounts:

,ride_id,pickup_location,dropoff_location,fare_amount,driver_rating,trip_duration_minutes
0,101,Downtown,Uptown,29.97,3.6,45
1,102,Airport,Downtown,23.62,4.5,59
2,103,Suburbia,Airport,22.66,3.0,49
3,104,Downtown,Uptown,40.23,3.8,13
4,105,Uptown,Downtown,22.66,4.0,11

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ride_id                22 non-null     int64
 1   pickup_location        22 non-null     object
 2   dropoff_location       22 non-null     object
 3   fare_amount            22 non-null     float64
 4   driver_rating          22 non-null     float64
 5   trip_duration_minutes  22 non-null     int64
dtypes: float64(2), int64(2), object(2)
memory usage: 1.2+ KB

In [20]:
# 1. Standardize pickup and dropoff locations
# Remove leading/trailing spaces and convert to title case for consistency
df_rideshare['pickup_location'] = df_rideshare['pickup_location'].str.strip().str.title()
df_rideshare['dropoff_location'] = df_rideshare['dropoff_location'].str.strip().str.title()

print("DataFrame after standardizing locations:")
display(df_rideshare.head())

DataFrame after standardizing locations:

,ride_id,pickup_location,dropoff_location,fare_amount,driver_rating,trip_duration_minutes
0,101,Downtown,Uptown,29.97,3.6,45
1,102,Airport,Downtown,23.62,4.5,59
2,103,Suburbia,Airport,NaN,3.0,49
3,104,Downtown,Uptown,40.23,3.8,13
4,105,Uptown,Downtown,22.66,4.0,11