<a href="https://colab.research.google.com/github/Udayan-12/AI.Assisted.Coding/blob/main/lab.17.3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Assuming the employee dataset is in a CSV file named 'employee_data.csv'
# If your file has a different name or path, please update it here.
try:
    df = pd.read_csv('employee_data.csv')
    print("Dataset loaded successfully.")
except FileNotFoundError:
    print("Error: 'employee_data.csv' not found. Please upload the file or provide the correct path/name.")
    # Creating a sample DataFrame for demonstration purposes if the file is not found
    data = {
        'employee_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy'],
        'salary': [70000, 80000, None, 60000, 95000, 72000, 88000, None, 65000, 78000],
        'designation': ['Software Engineer', 'Project Manager', 'Data Scientist', 'Software Engineer', 'HR Manager', 'Project Manager', 'Data Scientist', 'Software Engineer', 'HR Manager', 'Data Scientist'],
        'experience_years': [5, 10, 3, 4, 7, 6, None, 2, 8, 5],
        'employment_type': ['Full-time', 'Full-time', 'Contract', 'Full-time', 'Full-time', 'Contract', 'Full-time', 'Full-time', 'Part-time', 'Full-time'],
        'job_title': ['Software Engineer', 'Project Manager', 'Data Scientist', 'software engineer', 'HR Manager', 'project manager', 'Data Scientist', 'Software Engineer', 'hr manager', 'Data Scientist']
    }
    df = pd.DataFrame(data)
    print("A sample DataFrame has been created for demonstration.")


print("\nFirst 5 rows of the dataset:")
display(df.head())

print("\nDataset information (columns, non-null counts, dtypes):")
df.info()

Error: 'employee_data.csv' not found. Please upload the file or provide the correct path/name.
A sample DataFrame has been created for demonstration.

First 5 rows of the dataset:

,employee_id,name,salary,designation,experience_years,employment_type,job_title
0,1,Alice,70000.0,Software Engineer,5.0,Full-time,Software Engineer
1,2,Bob,80000.0,Project Manager,10.0,Full-time,Project Manager
2,3,Charlie,NaN,Data Scientist,3.0,Contract,Data Scientist
3,4,David,60000.0,Software Engineer,4.0,Full-time,software engineer
4,5,Eve,95000.0,HR Manager,7.0,Full-time,HR Manager

Dataset information (columns, non-null counts, dtypes):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   employee_id       10 non-null     int64
 1   name              10 non-null     object
 2   salary            8 non-null      float64
 3   designation       10 non-null     object
 4   experience_years  9 non-null      float64
 5   employment_type   10 non-null     object
 6   job_title         10 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 692.0+ bytes

In [4]:
# 3. Standardize text values (job titles in lowercase)
df['job_title'] = df['job_title'].str.lower()
print("\n'job_title' column after standardizing to lowercase:")
display(df[['job_title']].head())

# 4. Encode categorical features
# One-hot encoding for 'designation' and 'employment_type'
df = pd.get_dummies(df, columns=['designation', 'employment_type'], drop_first=True)

print("\nDataFrame after one-hot encoding categorical features:")
display(df.head())
df.info()

'job_title' column after standardizing to lowercase:

           job_title
0  software engineer
1    project manager
2     data scientist
3  software engineer
4         hr manager

DataFrame after one-hot encoding categorical features:

,employee_id,name,salary,experience_years,job_title,designation_HR Manager,designation_Project Manager,designation_Software Engineer,employment_type_Full-time,employment_type_Part-time
0,1,Alice,70000.0,5.0,software engineer,False,False,True,True,False
1,2,Bob,80000.0,10.0,project manager,False,True,False,True,False
2,3,Charlie,75000.0,3.0,data scientist,False,False,False,False,False
3,4,David,60000.0,4.0,software engineer,False,False,True,True,False
4,5,Eve,95000.0,7.0,hr manager,True,False,False,True,False

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   employee_id                    10 non-null     int64
 1   name                           10 non-null     object
 2   salary                         10 non-null     float64
 3   experience_years               10 non-null     float64
 4   job_title                      10 non-null     object
 5   designation_HR Manager         10 non-null     bool
 6   designation_Project Manager    10 non-null     bool
 7   designation_Software Engineer  10 non-null     bool
 8   employment_type_Full-time      10 non-null     bool
 9   employment_type_Part-time      10 non-null     bool
dtypes: bool(5), float64(2), int64(1), object(2)
memory usage: 582.0+ bytes

In [3]:
# 1. Handle missing values
# Impute missing 'salary' values with the median
median_salary = df['salary'].median()
df['salary'] = df['salary'].fillna(median_salary)
print(f"Missing 'salary' values imputed with median: {median_salary}")

# Impute missing 'experience_years' values with the median
median_experience = df['experience_years'].median()
df['experience_years'] = df['experience_years'].fillna(median_experience)
print(f"Missing 'experience_years' values imputed with median: {median_experience}")

print("\nAfter handling missing values:")
df.info()

# 2. Remove duplicate employee IDs
initial_rows = len(df)
df.drop_duplicates(subset=['employee_id'], inplace=True)
duplicates_removed = initial_rows - len(df)

if duplicates_removed > 0:
    print(f"\nRemoved {duplicates_removed} duplicate employee ID(s).")
else:
    print("\nNo duplicate employee IDs found.")

print("\nAfter removing duplicates:")
display(df.head())
df.info()

Missing 'salary' values imputed with median: 75000.0
Missing 'experience_years' values imputed with median: 5.0

After handling missing values:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   employee_id       10 non-null     int64
 1   name              10 non-null     object
 2   salary            10 non-null     float64
 3   designation       10 non-null     object
 4   experience_years  10 non-null     float64
 5   employment_type   10 non-null     object
 6   job_title         10 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 692.0+ bytes

No duplicate employee IDs found.

After removing duplicates:

,employee_id,name,salary,designation,experience_years,employment_type,job_title
0,1,Alice,70000.0,Software Engineer,5.0,Full-time,Software Engineer
1,2,Bob,80000.0,Project Manager,10.0,Full-time,Project Manager
2,3,Charlie,75000.0,Data Scientist,3.0,Contract,Data Scientist
3,4,David,60000.0,Software Engineer,4.0,Full-time,software engineer
4,5,Eve,95000.0,HR Manager,7.0,Full-time,HR Manager

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   employee_id       10 non-null     int64
 1   name              10 non-null     object
 2   salary            10 non-null     float64
 3   designation       10 non-null     object
 4   experience_years  10 non-null     float64
 5   employment_type   10 non-null     object
 6   job_title         10 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 692.0+ bytes

In [7]:
import pandas as pd
import numpy as np

# Creating a sample student performance DataFrame
np.random.seed(42)
data = {
    'student_id': range(1, 21),
    'exam_date': pd.to_datetime(pd.date_range(start='2023-01-15', periods=20, freq='W').strftime('%Y-%m-%d')).astype(str).tolist(), # Convert to string to simulate initial state
    'subject': np.random.choice(['Math', 'Science', 'English', 'History'], 20),
    'total_marks': np.random.randint(40, 100, 20).tolist(),
    'attendance_percentage': np.random.uniform(70, 100, 20).round(1).tolist()
}

# Create the DataFrame first
df_student = pd.DataFrame(data)

# Introduce some outliers in total_marks directly in the DataFrame
indices_to_change = np.random.choice(len(df_student['total_marks']), 2, replace=False)
df_student.loc[indices_to_change, 'total_marks'] = [10, 120] # Low and high outliers

print("Sample Student Performance DataFrame created:")
display(df_student.head())
print("\nDataFrame Information before preprocessing:")
df_student.info()


# 1. Convert 'exam_date' column into datetime format
df_student['exam_date'] = pd.to_datetime(df_student['exam_date'])
print("\n'exam_date' column converted to datetime:")
df_student.info()

# 2. Extract new features (month, semester, day)
df_student['exam_month'] = df_student['exam_date'].dt.month
df_student['exam_day_of_week'] = df_student['exam_date'].dt.day_name()

# For semester, let's define a simple rule (e.g., Jan-June as Semester 1, July-Dec as Semester 2)
df_student['semester'] = df_student['exam_date'].apply(lambda x: 'Semester 1' if x.month <= 6 else 'Semester 2')

print("\nDataFrame after extracting new time-based features:")
display(df_student.head())

Sample Student Performance DataFrame created:

   student_id   exam_date  subject  total_marks  attendance_percentage
0           1  2023-01-15  English           61                   71.4
1           2  2023-01-22  History           92                   99.2
2           3  2023-01-29     Math           41                   77.0
3           4  2023-02-05  English           63                   72.7
4           5  2023-02-12  English           83                   88.6

DataFrame Information before preprocessing:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             20 non-null     int64
 1   exam_date              20 non-null     object
 2   subject                20 non-null     object
 3   total_marks            20 non-null     int64
 4   attendance_percentage  20 non-null     float64
dtypes: float64(1), int64(2), object(2)
memory usage: 932.0+ bytes

'exam_date' column converted to datetime:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             20 non-null     int64
 1   exam_date              20 non-null     datetime64[ns]
 2   subject                20 non-null     object
 3   total_marks            20 non-null     int64
 4   attendance_percentage  20 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(1)
memory usage: 932.0+ bytes

DataFrame after extracting new time-based features:

,student_id,exam_date,subject,total_marks,attendance_percentage,exam_month,exam_day_of_week,semester
0,1,2023-01-15,English,61,71.4,1,Sunday,Semester 1
1,2,2023-01-22,History,92,99.2,1,Sunday,Semester 1
2,3,2023-01-29,Math,41,77.0,1,Sunday,Semester 1
3,4,2023-02-05,English,63,72.7,2,Sunday,Semester 1
4,5,2023-02-12,English,83,88.6,2,Sunday,Semester 1